name: bmi_algorithm
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.5.2
  - numpy=1.21.5
  - pandas=1.4.4
  - pip=21.2.4
  - python=3.9.12
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - seaborn=0.11.2
